// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetshopWebApp.Persistence;

#nullable disable

namespace PetshopWebApp.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    [Migration("20240501221952_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetshopWebApp.Models.Pet", b =>
                {
                    b.Property<int>("IdPet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_pet");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPet"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_birthday");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ds_pet");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ds_img_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("nm_pet");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("ds_port");

                    b.Property<string>("Race")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("ds_race");

                    b.Property<string>("Sex")
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR(1)")
                        .HasColumnName("ds_sex");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("ds_species");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("NUMBER(5, 2)")
                        .HasColumnName("nr_weight");

                    b.HasKey("IdPet");

                    b.ToTable("TB_PET");
                });

            modelBuilder.Entity("PetshopWebApp.Models.Petshop", b =>
                {
                    b.Property<int>("IdPetshop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_petshop");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPetshop"));

                    b.Property<string>("Cep")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("ds_cep");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("nm_petshop");

                    b.HasKey("IdPetshop");

                    b.ToTable("TB_PETSHOP");
                });

            modelBuilder.Entity("PetshopWebApp.Models.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_product");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ds_product");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("nm_product");

                    b.Property<decimal>("Price")
                        .HasPrecision(7, 2)
                        .HasColumnType("NUMBER(7, 2)")
                        .HasColumnName("vl_product");

                    b.HasKey("IdProduct");

                    b.ToTable("TB_PRODUCT");
                });

            modelBuilder.Entity("PetshopWebApp.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_review");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReview"));

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_published");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ds_review");

                    b.Property<decimal>("Stars")
                        .HasColumnType("NUMBER")
                        .HasColumnName("qt_stars");

                    b.HasKey("IdReview");

                    b.ToTable("TB_REVIEW");
                });

            modelBuilder.Entity("PetshopWebApp.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_user");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("DATE")
                        .HasColumnName("dt_birthday");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnName("ds_cpf");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ds_user");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("ds_email");

                    b.Property<string>("Gender")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("ds_gender");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ds_img_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("nm_user");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ds_password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("ds_phonenumber");

                    b.HasKey("IdUser");

                    b.ToTable("TB_USER");
                });
#pragma warning restore 612, 618
        }
    }
}
