// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetshopWebApp.Persistence;

#nullable disable

namespace PetshopWebApp.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetshopWebApp.Models.Pet", b =>
                {
                    b.Property<int>("IdPet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPet"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("DATE")
                        .HasColumnName("PetBirthday");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("PetDescription");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("PetImagePath");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("PetName");

                    b.Property<string>("Port")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("PetPort");

                    b.Property<string>("Race")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("PetRace");

                    b.Property<string>("Sex")
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR(1)")
                        .HasColumnName("PetSex");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("PetSpecies");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("NUMBER(5, 2)")
                        .HasColumnName("PetWeight");

                    b.HasKey("IdPet");

                    b.ToTable("TB_PET");
                });

            modelBuilder.Entity("PetshopWebApp.Models.Petshop", b =>
                {
                    b.Property<int>("IdPetshop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPetshop"));

                    b.Property<string>("Cep")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("PetshopCEP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("PetshopName");

                    b.HasKey("IdPetshop");

                    b.ToTable("TB_PETSHOP");
                });

            modelBuilder.Entity("PetshopWebApp.Models.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ProductDescription");

                    b.Property<decimal>("Price")
                        .HasPrecision(7, 2)
                        .HasColumnType("NUMBER(7, 2)")
                        .HasColumnName("ProductPrice");

                    b.HasKey("IdProduct");

                    b.ToTable("TB_PRODUCT");
                });

            modelBuilder.Entity("PetshopWebApp.Models.Review", b =>
                {
                    b.Property<int>("IdReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReview"));

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("DATE")
                        .HasColumnName("ReviewDatePublished");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("ReviewDescription");

                    b.Property<decimal>("Stars")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ReviewStars");

                    b.HasKey("IdReview");

                    b.ToTable("TB_REVIEW");
                });

            modelBuilder.Entity("PetshopWebApp.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("DATE")
                        .HasColumnName("UserBirthday");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("VARCHAR(14)")
                        .HasColumnName("UserCPF");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("UserDescription");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(80)")
                        .HasColumnName("UserEmail");

                    b.Property<string>("Gender")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("UserGender");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("UserImagePath");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("UserName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("UserPassword");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("UserPhoneNumber");

                    b.HasKey("IdUser");

                    b.ToTable("TB_USER");
                });
#pragma warning restore 612, 618
        }
    }
}
